// productsData.js - Centralized product data
export const productsData = [
  {
    id: 1,
    name: "12W Havells LED COB Light",
    price: 1475,
    minOrder: "50 Piece",
    model: "FLP-200",
    category: "COB Lights",
    rating: 4.8,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301855927/JB/NU/AW/60856849/havells-12-watt-cob-light-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301922997/HN/JO/XH/60856849/12w-havells-led-cob-light-500x500.jpeg",
    ],
    specifications: {
      Wattage: "12 W",
      Color: "Warm White",
      Brand: "Havells",
      "Usage/Application": "Office",
      "Base Type": "E40",
      "Color Temperature": "4000 K",
      "Working Temperature": "90 Degree",
      "Lighting Type": "LED",
      "Light Source": "Electric",
      Shape: "Round",
      "Body Material": "Aluminum",
      "IP Rating": "IP40",
      Warranty: "2 Year",
      "Input Voltage": "240 V",
      "Install Style": "Downlight",
      Frequency: "50 Hz",
      "Operating Temperature": "40 Degree Celsius",
      Height: "62 mm",
      "Cut out dimensions": "87 mm",
      "Model Number": "Crystal Neo",
    },
    additionalInfo: {
      "Light Type": "COB (Chip-on-Board) LED Downlighter",
      "Body Material": "Aluminum Body",
      "Design Type": "Swivel Downlighter",
      "Beam Angle": "36°",
      "Tilt Angle": "30° Adjustable",
      "Luminous Flux": "900 lumens",
    },
    features: [
      "Compact and Sleek Design",
      "Long 25,000-Hour Lifespan",
      "Efficient Heat Dissipation System",
      "Adjustable Swivel Beam Control",
      "Ideal for Domestic Ceilings",
    ],
    seo: {
      title: "200W Surya Flood Light - IP55 Rated LED Outdoor Lighting",
      description:
        "High-quality 200W LED flood light with IP55 rating, 120-degree beam angle, and aluminum construction. Perfect for outdoor illumination.",
      keywords:
        "LED flood light, 200W flood light, outdoor lighting, IP55 rated, Surya lighting",
    },
  },
  {
    id: 2,
    name: "Led Cob Chip",
    price: 90,
    minOrder: "100 Piece",
    model: "FLP-100",
    category: "COB LightS",
    rating: 4.6,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/9/343377162/EL/MB/EF/60856849/led-chip-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/9/343377164/QD/WY/YG/60856849/led-chip-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/9/343377166/PM/DN/LB/60856849/led-chip-500x500.jpg",
    ],
    specifications: {
      Power: "15 W",
      "Quantity Unit": "piece",
      Currency: "1",
      "Lighting Color": "Pure White",
      "Why do you need this": "For Reselling",
      "Country of Origin": "Made in India",
      Warranty: "2 Years",
    },
    additionalInfo: {
      Type: "Chip-on-Board (COB) LED Module",
      "Power Range": "1W – 100W (varies by model)",
      "Luminous Efficacy": "100–160 lm/W",
      "Viewing Angle": "120° – 160°",
      Lifespan: "30,000 – 50,000 Hours",
      "Operating Temperature": "-20°C to +60°C",
    },
    features: [
      "High Lumen Output Efficiency",
      "Low Power Consumption",
      "Wide Lighting Coverage",
      "Superior Heat Dissipation",
      "Ideal for Outdoor Applications",
    ],
    seo: {
      title: "100W LED Flood Light - IP65 Waterproof Outdoor Lighting",
      description:
        "Compact 100W LED flood light with IP65 waterproof rating, die-cast aluminum body, and 2-year warranty. Ideal for outdoor applications.",
      keywords:
        "100W LED light, outdoor flood light, IP65 waterproof, energy efficient lighting",
    },
  },
];
