// productsData.js - Centralized product data
export const productsData = [
  {
    id: 1,
    name: "200W Surya Flood Light",
    price: 7300,
    minOrder: "50 Piece",
    model: "FLP-200",
    category: "Flood Lights",
    rating: 4.8,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301915484/HB/JV/TK/60856849/200w-surya-flood-light-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301916434/MG/XI/NC/60856849/200w-surya-flood-light-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301963721/FT/NY/VL/60856849/200w-surya-flood-light-500x500.jpg",
    ],
    specifications: {
      "Usage/Application": "Flood Light",
      "Lighting Color": "Warm White",
      "IP Rating": "IP55",
      "Model Name/Number": "FLP-200",
      "Beam Angle": "120 Degree",
      Power: "200W",
      "Body Material": "Aluminum and Glass",
      "Lighting Type": "LED",
      "Input Voltage": "220V",
      Warranty: "1 Year",
      Frequency: "50 Hz",
    },
    additionalInfo: {
      Class: "Class-1",
      PF: ">0.95",
      Temperature: "55DegC",
      TC: "85DegC",
      "Made in": "India",
      Certification: "CE Certified",
    },
    features: [
      "Energy-efficient LED technology",
      "Weatherproof IP55 rated",
      "Wide 120-degree beam angle",
      "Durable aluminum and glass construction",
      "1 year warranty coverage",
    ],
    seo: {
      title: "200W Surya Flood Light - IP55 Rated LED Outdoor Lighting",
      description:
        "High-quality 200W LED flood light with IP55 rating, 120-degree beam angle, and aluminum construction. Perfect for outdoor illumination.",
      keywords:
        "LED flood light, 200W flood light, outdoor lighting, IP55 rated, Surya lighting",
    },
  },
  {
    id: 2,
    name: "150W Surya Flood Light",
    price: 5192,
    minOrder: "80 Piece",
    model: "FLP-100",
    category: "Flood Lights",
    rating: 4.6,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301874700/KZ/DA/FJ/60856849/surya-150-watt-light-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301874700/KZ/DA/FJ/60856849/surya-150-watt-light-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301874700/KZ/DA/FJ/60856849/surya-150-watt-light-500x500.jpg",
    ],
    specifications: {
      Wattage: "150W",
      "Lighting Color": "Cool Daylight",
      "Base Type": "B22",
      "IP Rating": "IP55",
      "Lighting Type": "LED",
      "Beam Angle": "120 Degree",
      "Usage/Application": "Street Light",
      "Working Temperature": "6000 K",
      "Body Material": "Aluminum and Glass",
      "Item Code": "LNRDK43V",
      Brand: "Surya",
      Warranty: "1 Years",
    },
    additionalInfo: {
      "Light Type": "Broad-beam, intense",
      "Primary Use": "Outdoor, stage lighting",
      "Beam Angle": "Wide coverage",
      "Light Source": "LED / Halogen",
      "Mounting Type": "Wall / Pole / Ground",
      Applications: "Sports, concerts, theater",
    },
    features: [
      "Broad-Beamed Illumination",
      "High-Intensity Lighting",
      "Outdoor Use",
      "Versatile Application",
      "Enhanced Visibility",
    ],
    seo: {
      title: "100W LED Flood Light - IP65 Waterproof Outdoor Lighting",
      description:
        "Compact 100W LED flood light with IP65 waterproof rating, die-cast aluminum body, and 2-year warranty. Ideal for outdoor applications.",
      keywords:
        "100W LED light, outdoor flood light, IP65 waterproof, energy efficient lighting",
    },
  },
  {
    id: 3,
    name: "50W Apra Kaixin LED Flood Light",
    price: 3800,
    minOrder: "90 Piece",
    model: "IFL-300",
    category: "Flood Lights",
    rating: 4.9,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301873776/PH/FC/NR/60856849/50w-apra-led-street-light-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301873776/PH/FC/NR/60856849/50w-apra-led-street-light-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301873776/PH/FC/NR/60856849/50w-apra-led-street-light-500x500.jpg",
    ],
    specifications: {
      Material: "Aluminum and Glass",
      "IP Rating": "IP66",
      "Working Temperature": "50 Degree",
      Color: "Warm White",
      Shape: "Square",
      Wattage: "50 W",
      "Usage/Application": "Flood Light",
      "Model Name/Number": "0050",
      "Beam Angle": "120 Degree",
      "Lighting Type": "LED",
      Warranty: "1 Years",
    },
    additionalInfo: {
      "Lighting Type": "Outdoor area lighting",
      "Main Purpose": "General illumination",
      "Common Uses": "Security, sports, wall washing",
      "User Types": "Pedestrian, vehicle, public spaces",
      "Mounting Height": "Medium to high",
      "Light Coverage": "Wide area",
    },
    features: [
      "Wide-Area Illumination",
      "Multi-Purpose Use",
      "Supports Safety",
      "Weather-Resistant Build",
      "Energy-Efficient Options",
    ],
    seo: {
      title: "300W Industrial LED Flood Light - Heavy Duty IP66 Rating",
      description:
        "Professional 300W industrial LED flood light with IP66 rating, 30,000 lumens output, and 3-year warranty. Perfect for industrial applications.",
      keywords:
        "300W industrial light, commercial flood light, IP66 rated, heavy duty LED",
    },
  },
  {
    id: 4,
    name: "Havells Max Pro Flood Light",
    price: 5310,
    minOrder: "80 Piece",
    model: "SSL-150",
    category: "Flood Lights",
    rating: 4.7,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301914255/EC/QO/AY/60856849/havells-max-pro-flood-light-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301914576/HF/EN/ET/60856849/havells-max-pro-flood-light-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301914807/ND/EO/YQ/60856849/havells-max-pro-flood-light-500x500.jpg",
    ],
    specifications: {
      Color: "Pure White",
      "Usage/Application": "Outdoor",
      "Lighting Color": "Warm White",
      "IP Rating": "IP55",
      "Model Name/Number": "Max Pro",
      "Beam Angle": "120 Degree",
      Power: "120W",
      "Body Material": "Aluminium",
      "Lighting Type": "LED",
      "Input Voltage": "220V",
      Frequency: "50 Hz",
      Brand: "Havells",

      Warranty: "1 Years",
    },
    additionalInfo: {
      "Beam Angle": "Up to 120°",
      Application: "Outdoor area lighting",
      "Light Spread": "Wide coverage",
      "Light Output": "High lumen output",
      Comparison: "Wider than spotlight",
      Efficiency: "Same wattage, wider beam",
    },
    features: [
      "Wide beam angle",
      "High lumen output",
      "Outdoor-ready design",
      "Energy-efficient performance",
      "Suitable for large areas",
    ],
    seo: {
      title: "150W LED Street Light - BIS Approved Highway Lighting",
      description:
        "Energy-efficient 150W LED street light with IP66 rating, 140-degree beam angle, and BIS certification. Ideal for streets and highways.",
      keywords:
        "LED street light, 150W street lamp, highway lighting, BIS approved",
    },
  },
  {
    id: 5,
    name: "100W Philips Flood Light",
    price: 3950,
    minOrder: "60 Piece",
    model: "SFL-50",
    category: "Flood Lights",
    rating: 4.5,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301873553/GN/TD/AD/60856849/philips-100-w-flood-light-500x500.jpeg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301873472/MC/BL/PO/60856849/philips-100-w-flood-light-500x500.jpeg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301963584/LH/GU/TC/60856849/100w-philips-flood-light-500x500.jpg",
    ],
    specifications: {
      "Usage/Application": "Outdoor",
      "Lighting Color": "Cool White",
      "IP Rating": "IP40",
      "Model Name/Number": "Smart Bright",
      "Beam Angle": "120 Degree",
      Power: "100W",
      "Body Material": "Aluminium And Glass",
      "Lighting Type": "LED",
      "Input Voltage": "220 V",
      "Operating Frequency": "60Hz",
      Brand: "Philips",
      Warranty: "1 Year",
    },
    additionalInfo: {
      Brand: "Philips",
      "Product Type": "LED Flood Light",
      "Driver Type": "Replaceable with 4kV Surge Protection",
      "Impact Resistance": "IK07",
      "Luminous Efficacy": "100 lm/W",
      "Ingress Protection": "IP65 (Dust & Water Resistant)",
    },
    features: [
      "Replaceable driver with 4kV surge protection",
      "IK07 impact resistance",
      "100 lumens per watt efficacy",
      "IP65-rated for dust and water",
      "Bright light in compact size",
    ],
    seo: {
      title: "50W Solar Flood Light - Zero Electricity Cost Garden Lighting",
      description:
        "Eco-friendly 50W solar LED flood light with 20000mAh battery, auto on/off sensor, and remote control. Perfect for gardens and outdoor spaces.",
      keywords:
        "solar flood light, 50W solar LED, garden lighting, eco-friendly lighting",
    },
  },
  {
    id: 6,
    name: "100W Havells Jeta Sturdy Flood Light",
    price: 3950,
    minOrder: "60 Piece",
    model: "STD-400",
    category: "Flood Lights",
    rating: 5.0,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301872945/AE/YU/BA/60856849/havells-flood-light-100-watt-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301873144/YW/GO/MK/60856849/havells-flood-light-100-watt-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301961696/UE/UI/YH/60856849/100w-havells-jeta-sturdy-flood-light-500x500.jpg",
    ],
    specifications: {
      Color: "Warm White",
      "Usage/Application": "Outdoor",
      "IP Rating": "IP55",
      "Model Name/Number": "Jeta Sturdy",
      "Beam Angle": "120 Degree",
      Power: "100W",
      "Body Material": "	Aluminum And Glass",
      "Lighting Type": "LED",
      "Input Voltage": "220V",
      Warranty: "2 Years",
      "Nominal Voltage": "240 V",
      Frequency: "50Hz",
      Brand: "Havells",
    },
    additionalInfo: {
      "Product Type": "Flood Light Bulb",
      "Lighting Purpose": "Outdoor area illumination",
      "Beam Angle": "Up to 120°",
      "Light Coverage": "Wide-area",
      "Light Output": "High lumen",
      "Wattage Efficiency": "Same as spotlight",
    },
    features: [
      "Wide beam angle",
      "High lumen output",
      "Efficient energy use",
      "Suitable for large areas",
      "Outdoor-ready design",
    ],
    seo: {
      title: "400W Stadium LED Light - Professional Sports Arena Lighting",
      description:
        "High-power 400W stadium LED light with 50,000 lumens, IP67 rating, anti-glare technology, and 5-year warranty. Ideal for sports arenas.",
      keywords:
        "stadium LED light, 400W sports light, arena lighting, high power LED",
    },
  },
];
