// productsData.js - Centralized product data
export const productsData = [
  {
    id: 1,
    name: "Surya SL-45W LED Street Light",
    price: 1680,
    minOrder: "50 Piece",
    model: "FLP-200",
    category: "Flood Lights",
    rating: 4.8,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301922562/WB/NZ/UL/60856849/45w-surya-led-street-light-500x500.jpeg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301922703/AW/ZJ/EJ/60856849/45w-surya-led-street-light-500x500.jpeg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/300693290/SV/TG/HU/60856849/45-w-surya-light-street-light-2--500x500.jpeg",
    ],
    specifications: {
      "Lighting Type": "LED",
      Certification: "CE",
      "Usage/Application": "Used for street lighting",
      "Input Voltage": "230V",
      "Model Name/Number": "SL-45W",
      "IP Rating": "IP33",
      "Lighting Color": "Warm Light",
      Frequency: "50 Hz",
      Power: "45Watt",
      Brand: "Surya",
      "Product Material": "Aluminum and Glass",
      Current: "200 A",
      Warranty: "1 Years",
    },
    additionalInfo: {
      "Product Name": "Surya SL-45W LED Street Light",
      "Power Rating": "45 Watts",
      "Ingress Protection": "IP66",
      "Electrical Class": "Class 1",
      "Power Factor": "PF > 0.55",
      "Ambient Temperature (TA)": "40°C",
    },
    features: [
      "High Lumen Output",
      "Weatherproof IP66 Design",
      "Energy Efficient Operation",
      "Durable Aluminum Housing",
      "Easy Installation Process",
    ],
    seo: {
      title: "200W Surya Flood Light - IP55 Rated LED Outdoor Lighting",
      description:
        "High-quality 200W LED flood light with IP55 rating, 120-degree beam angle, and aluminum construction. Perfect for outdoor illumination.",
      keywords:
        "LED flood light, 200W flood light, outdoor lighting, IP55 rated, Surya lighting",
    },
  },
  {
    id: 2,
    name: "Led Display Module",
    price: 1290,
    minOrder: "100 Piece",
    model: "FLP-100",
    category: "Flood Lights",
    rating: 4.6,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/9/343376949/ID/PC/YI/60856849/led-module-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/9/343376950/JS/UX/FU/60856849/led-module-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/9/343376951/VD/XM/YX/60856849/led-module-500x500.jpg",
    ],
    specifications: {
      "LED Color": "White",
      "Usage/Application": "Industrial",
      "Is It Waterproof": "Non Waterproof",
      "I Deal In": "New Only",
      "Country of Origin": "Made in India",
      Warranty: "1 Years",
      "Life Span": "30,000 – 50,000 hours",
      "Control Type": "Static or Programmable (for RGB)",
    },
    additionalInfo: {
      "Input Voltage": "12V DC / 24V DC (varies by model)",
      "Power Consumption": "0.72W – 1.5W per module (typical)",
      "LED Type": "SMD (Surface-Mounted Diodes)",
      "Working Temperature": "-20°C to +60°C",
      "Module Size": "Custom / Standard sizes available",
      "Beam Angle": "120° – 160°",
    },
    features: [
      "Compact and lightweight design",
      "Superior IP65 waterproof rating",
      "High luminous efficiency",
      "Long lifespan up to 50,000 hours",
      "2 years replacement warranty",
    ],
    seo: {
      title: "100W LED Flood Light - IP65 Waterproof Outdoor Lighting",
      description:
        "Compact 100W LED flood light with IP65 waterproof rating, die-cast aluminum body, and 2-year warranty. Ideal for outdoor applications.",
      keywords:
        "100W LED light, outdoor flood light, IP65 waterproof, energy efficient lighting",
    },
  },
  {
    id: 3,
    name: "60W Surya Pride Solar LED Street Light",
    price: 4250,
    minOrder: "25 Piece",
    model: "IFL-300",
    category: "Street Lights",
    rating: 4.9,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301921614/LC/OM/SY/60856849/60w-surya-solar-led-street-light-500x500.jpeg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/300695234/SM/WW/WU/60856849/solar-street-light-60-w-500x500.jpeg",
    ],
    specifications: {
      "Lighting Type": "LED",
      "Usage/Application": "Used for street lighting",
      "Input Voltage": "220V",
      "IP Rating": "IP55",
      Certification: "CE",
      "Model Name/Number": "Pride",
      "Body Material": "Aluminum and Glass",
      Wattage: "60W",
      "Brand Name": "Surya",
      Warranty: "1 Years",
    },
    additionalInfo: {
      "Product Name": "Surya Pride Solar LED Street Light",
      "Power Rating": "60 Watts",
      "Light Type": "Solar LED Street Light",
      Brand: "Surya Roshni Ltd.",
      "Solar Panel Type": "Monocrystalline / Polycrystalline Silicon",
      "Solar Panel Capacity": "12V, 80–100W (typical)",
    },
    features: [
      "High Lumen Solar Output",
      "Weatherproof IP66 Design",
      "Maintenance-Free LiFePO₄ Battery",
      "Automatic Dusk-to-Dawn Operation",
      "Durable Aluminum Body Construction",
    ],
    seo: {
      title: "300W Industrial LED Flood Light - Heavy Duty IP66 Rating",
      description:
        "Professional 300W industrial LED flood light with IP66 rating, 30,000 lumens output, and 3-year warranty. Perfect for industrial applications.",
      keywords:
        "300W industrial light, commercial flood light, IP66 rated, heavy duty LED",
    },
  },
  {
    id: 4,
    name: "Surya SL-72W LED Street Light",
    price: 2650,
    minOrder: "50 Piece",
    model: "SSL-150",
    category: "Flood Lights",
    rating: 4.7,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301921980/NP/HS/ZT/60856849/72w-surya-led-street-light-500x500.jpeg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/302007231/FS/JQ/HC/60856849/sl-72w-surya-led-street-light-500x500.jpeg",
    ],
    specifications: {
      "Lighting Type": "LED",
      Certification: "CE",
      "Usage/Application": "Used for street lighting",
      "Input Voltage": "220 V",
      "Model Name/Number": "SL-72-1",
      "IP Rating": "IP55",
      "Lighting Color": "Warm White",
      Frequency: "50Hz",
      "Battery Voltage": "220V",
      Power: "72W",
      Brand: "Suraya",
      Warranty: "1 Years",
    },
    additionalInfo: {
      "Lumen Output": "~7900–9300 lumens",
      "LED Type": "High Power SMD LEDs",
      "Color Temperature": "Cool White (5700K ±10%)",
      "Driver Efficiency": ">85%",
      Brand: "Surya Roshni Ltd.",
      "Input Voltage": "140–270V AC, 50Hz",
      "Power Factor": "PF > 0.9",
    },
    features: [
      "High-Efficiency LED Illumination",
      "Durable Die-Cast Housing",
      "Weatherproof IP66 Protection",
      "Energy-Saving Smart Design",
      "Ideal for Urban Lighting",
    ],
    seo: {
      title: "150W LED Street Light - BIS Approved Highway Lighting",
      description:
        "Energy-efficient 150W LED street light with IP66 rating, 140-degree beam angle, and BIS certification. Ideal for streets and highways.",
      keywords:
        "LED street light, 150W street lamp, highway lighting, BIS approved",
    },
  },
  {
    id: 5,
    name: "Surya SL-20W LED Street Light",
    price: 850,
    minOrder: "30 Piece",
    model: "SFL-50",
    category: "Flood Lights",
    rating: 4.5,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301953919/IL/UI/XE/60856849/20w-surya-led-street-light-500x500.jpeg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301953919/IL/UI/XE/60856849/20w-surya-led-street-light-500x500.jpeg",
    ],
    specifications: {
      "Lighting Type": "LED",
      Certification: "RoHS",
      "Usage/Application": "Used for street lighting",
      "Input Voltage": "220 V",
      "Model Name/Number": "SL-20W",
      "IP Rating": "IP55",
      "Lighting Color": "Warm Light",
      Frequency: "50Hz",
      Power: "20W",
      Brand: "Surya",
      "Product Material": "Aluminum and Glass",
      Warranty: "1 Year",
    },
    additionalInfo: {
      "Lumen Output": "~2000–2400 lumens",
      "LED Type": "High Power SMD LEDs",
      "Color Temperature": "Cool White (5700K ±10%)",
      Brand: "Surya Roshni Ltd.",
      "Input Voltage": "140–270V AC, 50Hz",
      "Power Factor": "PF > 0.9",
    },
    features: [
      "Compact and Energy Efficient",
      "Durable Aluminum Construction",
      "Weatherproof IP66 Protection",
      "Uniform Light Distribution",
      "Ideal for Pathway Lighting",
    ],
    seo: {
      title: "50W Solar Flood Light - Zero Electricity Cost Garden Lighting",
      description:
        "Eco-friendly 50W solar LED flood light with 20000mAh battery, auto on/off sensor, and remote control. Perfect for gardens and outdoor spaces.",
      keywords:
        "solar flood light, 50W solar LED, garden lighting, eco-friendly lighting",
    },
  },
];
