// productsData.js - Centralized product data
export const productsData = [
  {
    id: 1,
    name: "Surya SL-45W LED Street Light",
    price: 1680,
    minOrder: "50 Piece",
    model: "FLP-200",
    category: "Flood Lights",
    rating: 4.8,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301922562/WB/NZ/UL/60856849/45w-surya-led-street-light-500x500.jpeg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301922703/AW/ZJ/EJ/60856849/45w-surya-led-street-light-500x500.jpeg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/300693290/SV/TG/HU/60856849/45-w-surya-light-street-light-2--500x500.jpeg",
    ],
    specifications: {
      "Usage/Application": "Flood Light",
      "Lighting Color": "Warm White",
      "IP Rating": "IP55",
      "Model Name/Number": "FLP-200",
      "Beam Angle": "120 Degree",
      Power: "200W",
      "Body Material": "Aluminum and Glass",
      "Lighting Type": "LED",
      "Input Voltage": "220V",
      Warranty: "1 Year",
      Frequency: "50 Hz",
    },
    additionalInfo: {
      Class: "Class-1",
      PF: ">0.95",
      Temperature: "55DegC",
      TC: "85DegC",
      "Made in": "India",
      Certification: "CE Certified",
    },
    features: [
      "Energy-efficient LED technology",
      "Weatherproof IP55 rated",
      "Wide 120-degree beam angle",
      "Durable aluminum and glass construction",
      "1 year warranty coverage",
    ],
    seo: {
      title: "200W Surya Flood Light - IP55 Rated LED Outdoor Lighting",
      description:
        "High-quality 200W LED flood light with IP55 rating, 120-degree beam angle, and aluminum construction. Perfect for outdoor illumination.",
      keywords:
        "LED flood light, 200W flood light, outdoor lighting, IP55 rated, Surya lighting",
    },
  },
  {
    id: 2,
    name: "Led Display Module",
    price: 1290,
    minOrder: "100 Piece",
    model: "FLP-100",
    category: "Flood Lights",
    rating: 4.6,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/9/343376949/ID/PC/YI/60856849/led-module-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/9/343376950/JS/UX/FU/60856849/led-module-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/9/343376951/VD/XM/YX/60856849/led-module-500x500.jpg",
    ],
    specifications: {
      "Usage/Application": "Outdoor Lighting",
      "Lighting Color": "Cool White",
      "IP Rating": "IP65",
      "Model Name/Number": "FLP-100",
      "Beam Angle": "110 Degree",
      Power: "100W",
      "Body Material": "Die-Cast Aluminum",
      "Lighting Type": "LED",
      "Input Voltage": "220V",
      Warranty: "2 Years",
      Frequency: "50 Hz",
    },
    additionalInfo: {
      Class: "Class-1",
      PF: ">0.90",
      Temperature: "50DegC",
      TC: "80DegC",
      "Made in": "India",
      Certification: "CE & RoHS",
    },
    features: [
      "Compact and lightweight design",
      "Superior IP65 waterproof rating",
      "High luminous efficiency",
      "Long lifespan up to 50,000 hours",
      "2 years replacement warranty",
    ],
    seo: {
      title: "100W LED Flood Light - IP65 Waterproof Outdoor Lighting",
      description:
        "Compact 100W LED flood light with IP65 waterproof rating, die-cast aluminum body, and 2-year warranty. Ideal for outdoor applications.",
      keywords:
        "100W LED light, outdoor flood light, IP65 waterproof, energy efficient lighting",
    },
  },
  {
    id: 3,
    name: "60W Surya Pride Solar LED Street Light",
    price: 4250,
    minOrder: "25 Piece",
    model: "IFL-300",
    category: "Street Lights",
    rating: 4.9,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301921614/LC/OM/SY/60856849/60w-surya-solar-led-street-light-500x500.jpeg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/300695234/SM/WW/WU/60856849/solar-street-light-60-w-500x500.jpeg",
    ],
    specifications: {
      "Usage/Application": "Industrial/Commercial",
      "Lighting Color": "Natural White",
      "IP Rating": "IP66",
      "Model Name/Number": "IFL-300",
      "Beam Angle": "130 Degree",
      Power: "300W",
      "Body Material": "Heavy Duty Aluminum",
      "Lighting Type": "LED",
      "Input Voltage": "220-240V",
      Warranty: "3 Years",
      Frequency: "50-60 Hz",
    },
    additionalInfo: {
      Class: "Class-1",
      PF: ">0.97",
      Temperature: "60DegC",
      TC: "90DegC",
      "Made in": "India",
      Certification: "CE, RoHS, BIS",
    },
    features: [
      "Heavy-duty construction for industrial use",
      "Superior heat dissipation system",
      "Ultra-bright 30,000 lumens output",
      "Shock and vibration resistant",
      "3 years comprehensive warranty",
    ],
    seo: {
      title: "300W Industrial LED Flood Light - Heavy Duty IP66 Rating",
      description:
        "Professional 300W industrial LED flood light with IP66 rating, 30,000 lumens output, and 3-year warranty. Perfect for industrial applications.",
      keywords:
        "300W industrial light, commercial flood light, IP66 rated, heavy duty LED",
    },
  },
  {
    id: 4,
    name: "Surya SL-72W LED Street Light",
    price: 2650,
    minOrder: "50 Piece",
    model: "SSL-150",
    category: "Flood Lights",
    rating: 4.7,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301921980/NP/HS/ZT/60856849/72w-surya-led-street-light-500x500.jpeg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/302007231/FS/JQ/HC/60856849/sl-72w-surya-led-street-light-500x500.jpeg",
    ],
    specifications: {
      "Usage/Application": "Street/Highway Lighting",
      "Lighting Color": "Cool Day Light",
      "IP Rating": "IP66",
      "Model Name/Number": "SSL-150",
      "Beam Angle": "140 Degree",
      Power: "150W",
      "Body Material": "Aluminum Alloy",
      "Lighting Type": "LED",
      "Input Voltage": "220V AC",
      Warranty: "2 Years",
      Frequency: "50 Hz",
    },
    additionalInfo: {
      Class: "Class-1",
      PF: ">0.93",
      Temperature: "55DegC",
      TC: "85DegC",
      "Made in": "India",
      Certification: "BIS Approved",
    },
    features: [
      "Optimized for street and highway lighting",
      "Wide beam angle for maximum coverage",
      "Corrosion-resistant housing",
      "Energy saving up to 70%",
      "Easy installation and maintenance",
    ],
    seo: {
      title: "150W LED Street Light - BIS Approved Highway Lighting",
      description:
        "Energy-efficient 150W LED street light with IP66 rating, 140-degree beam angle, and BIS certification. Ideal for streets and highways.",
      keywords:
        "LED street light, 150W street lamp, highway lighting, BIS approved",
    },
  },
  {
    id: 5,
    name: "Surya SL-20W LED Street Light",
    price: 850,
    minOrder: "30 Piece",
    model: "SFL-50",
    category: "Flood Lights",
    rating: 4.5,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301953919/IL/UI/XE/60856849/20w-surya-led-street-light-500x500.jpeg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301953919/IL/UI/XE/60856849/20w-surya-led-street-light-500x500.jpeg",
    ],
    specifications: {
      "Usage/Application": "Garden/Outdoor Solar",
      "Lighting Color": "Warm White",
      "IP Rating": "IP65",
      "Model Name/Number": "SFL-50",
      "Beam Angle": "120 Degree",
      Power: "50W",
      "Body Material": "ABS + Aluminum",
      "Lighting Type": "LED Solar",
      Battery: "Lithium 20000mAh",
      Warranty: "1 Year",
      "Charging Time": "6-8 Hours",
    },
    additionalInfo: {
      "Solar Panel": "Polycrystalline 18V",
      "Backup Time": "10-12 Hours",
      "Light Sensor": "Auto On/Off",
      "Battery Life": "3-5 Years",
      "Made in": "India",
      Certification: "CE Certified",
    },
    features: [
      "100% solar powered - zero electricity cost",
      "Automatic dusk to dawn operation",
      "High capacity lithium battery",
      "Remote control included",
      "Eco-friendly and sustainable",
    ],
    seo: {
      title: "50W Solar Flood Light - Zero Electricity Cost Garden Lighting",
      description:
        "Eco-friendly 50W solar LED flood light with 20000mAh battery, auto on/off sensor, and remote control. Perfect for gardens and outdoor spaces.",
      keywords:
        "solar flood light, 50W solar LED, garden lighting, eco-friendly lighting",
    },
  },
];
