// productsData.js - Centralized product data
export const productsData = [
  {
    id: 1,
    name: "Havells Reo Utsav Ceiling Fan",
    price: 1680,
    minOrder: "50 Piece",
    model: "FLP-200",
    category: "Ceiling Fan",
    rating: 4.8,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301987614/IL/ZC/IV/60856849/havells-reo-utsav-ceiling-fan-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301872420/FY/KJ/SF/60856849/havells-reo-utsav-ceiling-fan-500x500.jpeg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301872505/MK/HK/PU/60856849/havells-reo-utsav-ceiling-fan-500x500.jpeg",
    ],
    specifications: {
      "Usage/Application": "Flood Light",
      "Lighting Color": "Warm White",
      "IP Rating": "IP55",
      "Model Name/Number": "FLP-200",
      "Beam Angle": "120 Degree",
      Power: "200W",
      "Body Material": "Aluminum and Glass",
      "Lighting Type": "LED",
      "Input Voltage": "220V",
      Warranty: "1 Year",
      Frequency: "50 Hz",
    },
    additionalInfo: {
      Class: "Class-1",
      PF: ">0.95",
      Temperature: "55DegC",
      TC: "85DegC",
      "Made in": "India",
      Certification: "CE Certified",
    },
    features: [
      "Energy-efficient LED technology",
      "Weatherproof IP55 rated",
      "Wide 120-degree beam angle",
      "Durable aluminum and glass construction",
      "1 year warranty coverage",
    ],
    seo: {
      title: "200W Surya Flood Light - IP55 Rated LED Outdoor Lighting",
      description:
        "High-quality 200W LED flood light with IP55 rating, 120-degree beam angle, and aluminum construction. Perfect for outdoor illumination.",
      keywords:
        "LED flood light, 200W flood light, outdoor lighting, IP55 rated, Surya lighting",
    },
  },
  {
    id: 2,
    name: "Orient Electric Gratia Ceiling Fan",
    price: 1475,
    minOrder: "100 Piece",
    model: "FLP-100",
    category: "Ceiling Fan",
    rating: 4.6,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301878792/WN/SY/PT/60856849/orient-fan-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301878798/VO/SM/EY/60856849/orient-fan-500x500.jpg",
    ],
    specifications: {
      "Usage/Application": "Outdoor Lighting",
      "Lighting Color": "Cool White",
      "IP Rating": "IP65",
      "Model Name/Number": "FLP-100",
      "Beam Angle": "110 Degree",
      Power: "100W",
      "Body Material": "Die-Cast Aluminum",
      "Lighting Type": "LED",
      "Input Voltage": "220V",
      Warranty: "2 Years",
      Frequency: "50 Hz",
    },
    additionalInfo: {
      Class: "Class-1",
      PF: ">0.90",
      Temperature: "50DegC",
      TC: "80DegC",
      "Made in": "India",
      Certification: "CE & RoHS",
    },
    features: [
      "Compact and lightweight design",
      "Superior IP65 waterproof rating",
      "High luminous efficiency",
      "Long lifespan up to 50,000 hours",
      "2 years replacement warranty",
    ],
    seo: {
      title: "100W LED Flood Light - IP65 Waterproof Outdoor Lighting",
      description:
        "Compact 100W LED flood light with IP65 waterproof rating, die-cast aluminum body, and 2-year warranty. Ideal for outdoor applications.",
      keywords:
        "100W LED light, outdoor flood light, IP65 waterproof, energy efficient lighting",
    },
  },
  {
    id: 3,
    name: "BLDC Ceiling Fan",
    price: 2099,
    minOrder: "25 Piece",
    model: "IFL-300",
    category: "Ceiling Fan",
    rating: 4.9,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301878798/VO/SM/EY/60856849/orient-fan-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301878792/WN/SY/PT/60856849/orient-fan-500x500.jpg",
    ],
    specifications: {
      "Usage/Application": "Industrial/Commercial",
      "Lighting Color": "Natural White",
      "IP Rating": "IP66",
      "Model Name/Number": "IFL-300",
      "Beam Angle": "130 Degree",
      Power: "300W",
      "Body Material": "Heavy Duty Aluminum",
      "Lighting Type": "LED",
      "Input Voltage": "220-240V",
      Warranty: "3 Years",
      Frequency: "50-60 Hz",
    },
    additionalInfo: {
      Class: "Class-1",
      PF: ">0.97",
      Temperature: "60DegC",
      TC: "90DegC",
      "Made in": "India",
      Certification: "CE, RoHS, BIS",
    },
    features: [
      "Heavy-duty construction for industrial use",
      "Superior heat dissipation system",
      "Ultra-bright 30,000 lumens output",
      "Shock and vibration resistant",
      "3 years comprehensive warranty",
    ],
    seo: {
      title: "300W Industrial LED Flood Light - Heavy Duty IP66 Rating",
      description:
        "Professional 300W industrial LED flood light with IP66 rating, 30,000 lumens output, and 3-year warranty. Perfect for industrial applications.",
      keywords:
        "300W industrial light, commercial flood light, IP66 rated, heavy duty LED",
    },
  },
];
