// productsData.js - Centralized product data
export const productsData = [
  {
    id: 1,
    name: "Havells Reo Utsav Ceiling Fan",
    price: 1680,
    minOrder: "90 Piece",
    model: "FLP-200",
    category: "Ceiling Fan",
    rating: 4.8,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301987614/IL/ZC/IV/60856849/havells-reo-utsav-ceiling-fan-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301872420/FY/KJ/SF/60856849/havells-reo-utsav-ceiling-fan-500x500.jpeg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301872505/MK/HK/PU/60856849/havells-reo-utsav-ceiling-fan-500x500.jpeg",
    ],
    specifications: {
      "Number of Blades": "3 Blades",
      Speed: "350 RPM",
      Warranty: "2 Years",
      "Noise Level": "60 dB",
      "Model No": "Reo Utsav",
      "Phase Type": "Single Phase",
      Power: "100W",
      Brand: "Havells",
      Color: "Brown",
      "Sweep Size": "1200 mm",
      "Blade Length (Sweep)": "600 mm",
    },
    additionalInfo: {
      Model: "Reo Utsav Ceiling Fan",
      "Build Quality": "Safe, reliable, durable",
      Speed: "High speed",
      RPM: "400 RPM",
      "Air Delivery": "Superior performance",
      "Bearing Type": "Double ball bearing",
    },
    features: [
      "Safe and durable design",
      "High-speed operation",
      "400 RPM motor",
      "Superior air delivery",
      "Double ball bearing motor",
    ],
    seo: {
      title: "200W Surya Flood Light - IP55 Rated LED Outdoor Lighting",
      description:
        "High-quality 200W LED flood light with IP55 rating, 120-degree beam angle, and aluminum construction. Perfect for outdoor illumination.",
      keywords:
        "LED flood light, 200W flood light, outdoor lighting, IP55 rated, Surya lighting",
    },
  },
  {
    id: 2,
    name: "Orient Electric Gratia Ceiling Fan",
    price: 1475,
    minOrder: "70 Piece",
    model: "FLP-100",
    category: "Ceiling Fan",
    rating: 4.6,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301878792/WN/SY/PT/60856849/orient-fan-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301878798/VO/SM/EY/60856849/orient-fan-500x500.jpg",
    ],
    specifications: {
      "Sweep Size": "1200 mm",
      "Blade Length (Sweep)": "1200 mm",
      "Number of Blades": "3 Blades",
      Speed: "380 RPM",
      Warranty: "1 Year",
      "Noise Level": "65 dB",
      "Air Delivery": "230cmm",
      Brand: "Orient",
      Power: "32 W",
      Color: "Beige",
    },
    additionalInfo: {
      Brand: "Orient Electric",
      Model: "Gratia Ceiling Fan",
      Type: "Decorative ceiling fan",
      "Motor Type": "100% Copper Motor",
      "Motor Strength": "14 Pole (14P)",
      "Bearing Type": "Double ball bearing",
    },
    features: [
      "Decorative ceiling design",
      "14-pole strong motor",
      "100% copper winding",
      "Double ball bearing system",
      "Durable and long-lasting",
    ],
    seo: {
      title: "100W LED Flood Light - IP65 Waterproof Outdoor Lighting",
      description:
        "Compact 100W LED flood light with IP65 waterproof rating, die-cast aluminum body, and 2-year warranty. Ideal for outdoor applications.",
      keywords:
        "100W LED light, outdoor flood light, IP65 waterproof, energy efficient lighting",
    },
  },
  {
    id: 3,
    name: "BLDC Ceiling Fan",
    price: 2099,
    minOrder: "70 Piece",
    model: "IFL-300",
    category: "Ceiling Fan",
    rating: 4.9,
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301878798/VO/SM/EY/60856849/orient-fan-500x500.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2023/4/301878792/WN/SY/PT/60856849/orient-fan-500x500.jpg",
    ],
    specifications: {
      "Blade Length (Sweep)": "1200 mm",
      Speed: "240 RPM",
      Warranty: "1 Year",
      "Number of Blades": "3 Blades",
      "Country of Origin": "Made in India",
    },
    additionalInfo: {
      "Fan Type	BLDC": "(Brushless DC) Fan",
      "Motor Type": "Brushless motor",
      Technology: "Electronic motor control",
      "Energy Efficiency": "Low power consumption",
      Durability: "Long-lasting",
      Maintenance: "Low maintenance",
    },
    features: [
      "Energy-efficient operation",
      "Long motor life",
      "Fewer moving parts",
      "Low maintenance",
      "Advanced brushless motor",
    ],
    seo: {
      title: "300W Industrial LED Flood Light - Heavy Duty IP66 Rating",
      description:
        "Professional 300W industrial LED flood light with IP66 rating, 30,000 lumens output, and 3-year warranty. Perfect for industrial applications.",
      keywords:
        "300W industrial light, commercial flood light, IP66 rated, heavy duty LED",
    },
  },
];
